### ISSUE TITLE
Header is cutting off on Android

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/gurmukhi-word-link#60]

**Comment by MySmilingTurban** [comment]
please share a screenshot for the issue for reference

**Comment by pdvsingh** [comment]
![Screenshot_20220630-163344](https://user-images.githubusercontent.com/44109213/176795370-def79a6f-78bd-4f96-91e5-34087250c5da.png)
![Screenshot_20220630-163328](https://user-images.githubusercontent.com/44109213/176795371-58a1642d-dd16-4d46-bd4c-992e081eda0a.png)
