### ISSUE TITLE
Track what game are users playing more

### ISSUE THREAD

**Issue by Hamoric13** [KhalisFoundation/gurmukhi-word-link#65]
As a Product Owner, I want to track what games are the users playing more so that we can make changes to the less played game and track if the changes increase play time.

This will help us understand user preferences and based on this data we can roll out changes to the less played game as well.

**Comment by prebhdevsingh** [comment]
Doesn't time tracking (#66) provide you with the same insight as this one?

**Comment by MySmilingTurban** [comment]
this metric was set to know which game is more opened from menu
